QOL: Move skin debug setting from each controller skin to a global setting
rileytestut/Delta pull request #141
Opened 2021-07-17 06:34 UTC by ianclawson

This is mainly for ease of use in testing out new Controller Skins, as well as efforts in updating the skin spec.

DeltaCore PR: https://github.com/rileytestut/DeltaCore/pull/34

Trello Card: https://trello.com/c/IGSv3tcf

2021-07-19 23:55 UTC, rileytestut requested changes

2021-07-19 23:55 UTC, rileytestut commented on Delta/Emulation/GameViewController.swift
> +        self.controllerView.isControllerSkinDebugModeEnabled = Settings.isControllerSkinDebugModeEnabled
As mentioned in DeltaCore PR, I think this should be `.isDebugModeEnabled`
```suggestion
        self.controllerView.isDebugModeEnabled = Settings.isControllerSkinDebugModeEnabled
```

2021-07-19 23:55 UTC, rileytestut commented on Delta/Settings/SettingsViewController.swift
> +        tapGesture.numberOfTapsRequired = 13
Happy to have this feature hidden for now, but 13 might be a bit high even for a hidden feature. IMO ~3 taps would be enough for a relatively harmless feature like this.
```suggestion
        tapGesture.numberOfTapsRequired = 3
```

2021-07-21 15:43 UTC, ianclawson commented
@rileytestut thanks for the review! Agree with your suggestions and just implemented them, ready for another pass 👍

2022-08-06 14:12 UTC, ianclawson commented
Closing this to clean up my work list of Open PRs

2022-08-06 14:12 UTC, ianclawson commented
Closing this to clean up my work list of Open PRs

2022-08-06 14:12 UTC, closed without merging