Experimental Feature: Game Screenshots
rileytestut/Delta pull request #242
Opened 2023-04-25 00:48 UTC by LitRitt

2023-04-25 17:04 UTC, rileytestut requested changes
Thanks for breaking these PRs up! Overall looks good to me, just have one note about the implementation of `isAuthorized` that could result in minor bug, but once that’s fixed I’d be happy to merge 🙂

Also I appreciate you putting the PHPhotoLibrary stuff in an extension! The more isolated changes are from the rest of the app, the better 👍

2023-04-25 17:04 UTC, rileytestut commented on Delta/Emulation/GameViewController.swift
> +           PHPhotoLibrary.isAuthorized
See my note below, this is a potential bug.

2023-04-26 17:33 UTC, rileytestut approved these changes
Nice approach, passing in a closure that's only run if authorized is a good idea. 

Thanks for these changes, everything looks good to me! Will merge this in along with #241 once everything is merged into `develop` branch 👍

2023-04-28 19:35 UTC, merged

2025-02-21 23:14 UTC, takashiou reviewed
好👍

2026-02-07 21:15 UTC, jesn459 reviewed
Gracias