[Experimental Feature] Alternate App Icons
rileytestut/Delta pull request #259
Opened 2023-07-21 05:45 UTC by LitRitt

Mark the type contribution you are making:

- [X] Experimental feature (new functionality that can be selectively enabled/disabled)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Description

Adds assets for alternate icons, an extension to retrieve icon images as `UIImage`s, code to handle changing app icon, and feature / options.

# Testing

- iPhone 12 Pro, iOS 16.5.1
- iPad mini 6, iOS 16.5.1

# Checklist
**General (All PRs)**
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I've tested my changes with different device + OS version configurations

**Experimental Feature-specific** 
- [X] Added property to `ExperimentalFeatures` struct annotated with `@Feature`
- [X] Uses `@Option`'s to persist all feature-related data
- [X] Locked *all* behavior changes behind `ExperimentalFeatures.shared.[feature].isEnabled` runtime check
- [X] Isolates changes to separate files as much as possible (e.g. via Swift extensions)

2023-08-01 18:04 UTC, rileytestut requested changes
Awesome work, this will be a great feature to have! My only real note is a request to move the actual app-icon-changing logic out of `SettingsViewController`, but otherwise the code itself + logic all look good to me 👍

2023-08-01 18:04 UTC, rileytestut commented on Delta/Experimental Features/Features/AlternateAppIcons.swift
> +        case .inverted, .gba4ios, .skin, .pixelated: return "LitRitt"
```suggestion
        case .normal: return "Caroline Moore"
        case .gba4ios: return "Paul Thorsen"
        case .inverted, .skin, .pixelated: return "LitRitt"
```

Caroline made the default Delta icon, whereas Paul made the GBA4iOS icon :)

2023-08-03 19:34 UTC, LitRitt commented on Delta/Settings/Settings.swift
> +    static let experimentalFeatures = ExperimentalFeatures.shared
Got it. Changed that.

2023-08-03 19:37 UTC, LitRitt commented
Addressed all your comments and suggestions. All the code is now located within `AlternateAppIcons.swift`

2023-11-08 19:35 UTC, closed without merging